//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sideTrade.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public int LogTypeId { get; set; }
        public string Value { get; set; }
        public DateTime CreatedOn { get; set; }
        public Nullable<int> ProfileId { get; set; }
    
        public virtual LogType LogType { get; set; }
    }
}
