//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sideTrade.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileMapping
    {
        public int Id { get; set; }
        public int ProfileId { get; set; }
        public int ProfileTypeId { get; set; }
        public DateTime CreatedOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual ProfileType ProfileType { get; set; }
    }
}
