//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sideTrade.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SideTrade_DBEntities : DbContext
    {
        public SideTrade_DBEntities()
            : base("name=SideTrade_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FileManager> FileManager { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<ProfileMapping> ProfileMapping { get; set; }
        public virtual DbSet<ProfileType> ProfileType { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<NotificationType> NotificationType { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<LogType> LogType { get; set; }
        public virtual DbSet<FileManagerType> FileManagerType { get; set; }
    }
}
